Output order.gif

Require ehmodpack

Set Shell bash

Set Theme "Catppuccin Mocha"
Set FontSize 16
Set Width 1280
Set Height 720
Set Framerate 12
Set PlaybackSpeed 3
Set LoopOffset 20%
Set Margin 15
Set MarginFill "#657BF2"
Set Padding 10
Set BorderRadius 10
Set WindowBar Colorful
Set CursorBlink false
Set TypingSpeed 25ms
Set WaitTimeout 300s

Sleep 2s

Sleep 500ms
Type "ehmodpack order"
Sleep 1s
Enter
Sleep 1s
Sleep 3s

Space
Sleep 900ms
Enter
Sleep 2s

Down
Sleep 600ms
Enter
Sleep 2s

Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter
Show
Sleep 2s

Down
Sleep 500ms
Down
Sleep 500ms
Enter
Show
Sleep 2s

Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 3s

Up
Sleep 500ms
Enter
Show
Sleep 2s

Sleep 500ms
Hide
Type "clear"
Sleep 1s
Enter
Show
Sleep 2s