Output readme.gif

Require ehmodpack

Set Shell bash

Set Theme "Catppuccin Mocha"
Set FontSize 16
Set Width 1280
Set Height 720
Set Framerate 12
Set PlaybackSpeed 2
Set LoopOffset 20%
Set Margin 15
Set MarginFill "#657BF2"
Set Padding 10
Set BorderRadius 10
Set WindowBar Colorful
Set CursorBlink false
Set TypingSpeed 200ms
Set WaitTimeout 120s

Sleep 3s

Sleep 1s
Type "ehmodpack new eh-demo -m 1.21.11 -l fabric --workflow source --git --force"
Sleep 2s
Enter
Wait+Screen /visit your project/
Sleep 3s

Sleep 1s
Type "cd eh-demo"
Sleep 2s
Enter
Wait
Sleep 2s

Sleep 1s
Type "ehmodpack browse"
Sleep 2s
Enter
Wait+Screen /browsing by/
Sleep 6s

Down
Sleep 2s
Enter
Sleep 8s

Down
Sleep 2s
Enter
Sleep 6s

Up
Sleep 2s
Enter
Sleep 5s

Type "cls"
Sleep 2s
Enter
Sleep 5s