Output readme.gif

Require ehmodpack

Set Shell bash

Set Theme "Catppuccin Mocha"
Set FontSize 16
Set Width 1280
Set Height 720
Set Framerate 12
Set PlaybackSpeed 3
Set LoopOffset 20%
Set Margin 15
Set MarginFill "#657BF2"
Set Padding 10
Set BorderRadius 10
Set WindowBar Colorful
Set CursorBlink false
Set TypingSpeed 75ms
Set WaitTimeout 300s

Sleep 2s

Sleep 500ms
Type "ehmodpack new eh-demo -m 1.21.11 -l fabric --workflow source --git --force"
Sleep 1s
Enter
Wait+Screen /visit your project/
Sleep 2s

Sleep 500ms
Type "cd eh-demo"
Sleep 1s
Enter
Wait
Sleep 1s

Sleep 500ms
Type "ehmodpack browse"
Sleep 1s
Enter
Wait+Screen /browsing by/
Sleep 3s

Down
Sleep 1s
Enter
Sleep 3s

Down
Sleep 1s
Enter
Show
Sleep 2s

Up
Sleep 1s
Enter
Show
Sleep 2s

Hide
Type "clear"
Sleep 1s
Enter
Show
Sleep 2s